recsys/recsys/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('modulerec.urls')),
    path('auth/', include('moduleauth.urls')),
    path('rate/', include('modulerate.urls')),
]

recsys/modulerate/models.py
from django.db import models
from modulerec.models import Product
from moduleauth.models import Profile
from django.db.models import Avg
from django.contrib.auth.models import User


# Create your models here.
class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='ratings')
    value = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    goal = models.CharField(max_length=20, choices=[
        ('gain', 'Набор'), 
        ('lose', 'Похудение'), 
        ('main', 'Поддержание')]
        )

    def average_rating_for_goal(self, goal):
        return self.ratings.filter(goal=goal).aggregate(Avg('value'))['value__avg'] or 0

    def __str__(self):
        return f'{self.user.username} - {self.product.name} - {self.value}'

recsys/templates/catalog.html
{% load static %}

<html lang="ru">

    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Good Food. Catalog</title>
        <link rel="icon" type="image" href="{% static 'assets/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        <link rel="stylesheet" href="{% static 'styles/catalog.css' %}">
    </head>

    <body>
        
        <div id="heading">
            <span>Good Food</span>
        </div>

        <div id="body">

            <div class="navbar">
                <a href="{% url 'index' %}" class="nav-button">Главная</a>
                <a href="{% url 'catalog' %}" class="nav-button">Каталог<div class="nav-button--circle"></div></a>
                {% if user.is_authenticated %}
                    <a href="{% url 'foru' %}" class="nav-button restricted">Для вас</a>
                {% else %}
                    <script src="{ static 'utils/restrict.js' }"></script>
                {% endif %}

                <div class="auth-buttons">
                    {% if user.is_authenticated %}
                        <a href="{% url 'profile' %}" class="auth-button">Профиль</a>
                        <a href="{% url 'logout' %}" class="auth-button">Выйти</a>
                    {% else %}
                        <a href="{% url 'signin' %}" class="auth-button">Вход</a>
                        <a href="{% url 'signup' %}" class="auth-button">Регистрация</a>
                    {% endif %}
                </div>
            </div>

            <button id="toggleFormsButton">Показать/Скрыть формы</button>
            <script src="{% static 'utils/displayetoggle.js' %}"></script>

            <script src="{% static 'utils/catalog.js' %}"></script>
            <div class="catalog-content">
                <div class="catalog-navbar">
                    {% for category in categories %}
                        <button data-target="#{{ category.name }}" class="product-button">
                            {% if category.ru_name %}
                                {{ category.ru_name }}
                                {% if user.is_authenticated %}
                                    <form method="post" action="{% url 'include_category' category.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="include-btn">+</button>
                                    </form>
                                    <form method="post" action="{% url 'exclude_category' category.id %}">
                                        {% csrf_token %}
                                        <button type="submit" class="exclude-btn">–</button>
                                    </form>
                                {% endif %}
                            {% else %}
                                {{ category.name }}
                            {% endif %}
                        </button>
                    {% endfor %}
                </div>

                <div class="content-area">
                    {% for category in categories %}
                        <div id="{{ category.name }}" class="content-block {% if forloop.first %}active{% endif %}">
                            <div class="product-grid">
                                {% for product in products %}
                                    {% if product.category == category %}
                                        <div class="product-card">
                                            <h3>{{ product.name }}</h3>
                                            <a href="{% url 'product_detail' product.id %}"><p>Рейтинг: {{ product.average_rating|floatformat:1 }}</p></a>
                                            <div class="forms-container" style="display: none;">
                                                {% if user.is_authenticated %}
                                                    {% if product in request.user.profile.excluded_products.all %}
                                                        <form method="post" action="{% url 'include_product' product.id %}" style="display:inline;">
                                                            {% csrf_token %}
                                                            <button type="submit" class="include-btn">+</button>
                                                        </form>
                                                    {% else %}
                                                        <form method="post" action="{% url 'exclude_product' product.id %}" style="display:inline;">
                                                            {% csrf_token %}
                                                            <button type="submit" class="exclude-btn">–</button>
                                                        </form>
                                                    {% endif %}
                                                {% endif %}
                                            </div>                                                                       
                                            <h4>Состав: <br>
                                                Белки: {{ product.proteins }}<br>
                                                Жиры: {{ product.fats }}<br>
                                                Углеводы: {{ product.carbohydrates }}<br>
                                                Калорийность: {{ product.caloricity }}
                                            </h4>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

        </div>

    </body>

</html>

recsys/templates/foru.html
{% load static %}

<html lang="ru">

    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Good Food. profile</title>
        <link rel="icon" type="image" href="{% static 'assets/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        <link rel="stylesheet" href="{% static 'styles/foru.css' %}">
    </head>

    <body>
        
        <div id="heading">
            <span>Good Food</span>
        </div>

        <div id="body">
            <div class="navbar">
                <a href="{% url 'index' %}" class="nav-button">Главная</a>
                <a href="{% url 'catalog' %}" class="nav-button">Каталог</a>
                {% if user.is_authenticated %}
                    <a href="#" class="nav-button restricted">Для вас<div class="nav-button--circle"></div></a>
                {% else %}
                    <script src="{ static 'utils/restrict.js' }"></script>
                {% endif %}
                
                <div class="auth-buttons">
                    {% if user.is_authenticated %}
                        <a href="{% url 'profile' %}" class="auth-button">Профиль</a>
                        <a href="{% url 'logout' %}" class="auth-button">Выйти</a>
                    {% else %}
                        <a href="{% url 'signin' %}" class="auth-button">Вход</a>
                        <a href="{% url 'signup' %}" class="auth-button">Регистрация</a>
                    {% endif %}
                </div>
            </div>
            
            <div class="container">
                <div class="left-panel">
                    <div class="user-info">
                        {% if user.is_authenticated %}
                            {% if user %}
                                <p>Ваши данные: </p>
                                <ul>
                                    <li>Пол: {{ user.profile.get_sex_display }}</li>
                                    <li>Возраст: {{ user.profile.age }} лет</li>
                                    <li>Рост: {{ user.profile.height }} см</li>
                                    <li>Вес: {{ user.profile.weight }} кг</li>
                                    <li>Цель: {{ user.profile.get_goal_display }}</li>
                                </ul>
                                <a href="{% url 'profile' %}" class="btn">Изменить данные</a>
                            {% else %}
                                <p>Заполните профиль для получения рекомендаций</p>
                                <a href="{% url 'profile' %}" class="btn">Перейти к профилю</a>
                            {% endif %}
                        {% endif %}
                    </div>
        
                    <div class="goal-selection">
                        <form method="post">
                            <label for="">Выберите цель:</label>
                            {% csrf_token %}
                            {{ goal_form.goal }}
                            <button type="submit" class="btn">Применить цель</button>
                        </form>
                    </div>

                    <div class="rec-info">
                        {% if user.is_authenticated %}
                            {% if user.profile %}
                                <p>Базовый метаболизм: {{ macros.calories|floatformat:0 }} ккал</p>
                                <p>Рекомендуемая норма:</p>
                                <ul>
                                    <li>Белки: {{ macros.proteins|floatformat:1 }} г</li>
                                    <li>Жиры: {{ macros.fats|floatformat:1 }} г</li>
                                    <li>Углеводы: {{ macros.carbohydrates|floatformat:1 }} г</li>
                                </ul>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                    
                <div class="products">
                    {% for product in products %}
                        <div class="product-card">
                            <h3>{{ product.name }}</h3>
                                <p>Рейтинг: {{ product.average_rating|floatformat:1 }}</p>
                                Белки: {{ product.proteins }}<br>
                                Жиры: {{ product.fats }}<br>
                                Углеводы: {{ product.carbohydrates }}<br>
                                Калорийность: {{ product.caloricity }}
                        </div>
                    {% empty %}
                        <p>Нет продуктов для вашей цели</p>
                    {% endfor %}
                </div>
            </div>

        </div>

    </body>

</html>

recsys/templates/index.html
{% load static %}

<html lang="ru">

    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Good Food</title>
        <link rel="icon" type="image" href="{% static 'assets/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        <link rel="stylesheet" href="{% static 'styles/index.css' %}">
    </head>

    <body>
        
        <div id="heading">
            <span>Good Food</span>
        </div>

        <div id="body">
            <div class="navbar">
                <a href="{% url 'index' %}" class="nav-button">Главная<div class="nav-button--circle"></div></a>
                <a href="{% url 'catalog' %}" class="nav-button">Каталог</a>
                <a href="#" class="nav-button">Для вас</a>
                
                <div class="auth-buttons">
                    {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}" class="auth-button">Профиль</a>
                    <a href="{% url 'logout' %}" class="auth-button">Выйти</a>
                    {% else %}
                    <a href="{% url 'signin' %}" class="auth-button">Вход</a>
                    <a href="{% url 'signup' %}" class="auth-button">Регистрация</a>
                    {% endif %}
                </div>

            </div>

            <div class="main-info1">
                <p class="h1text"><img class="info1-img" src="{% static 'assets/icon.png' %}" alt="">Разнообразие еды</p>
                <p class="text">Больше не придётся есть одно и тоже. В нашем каталоге вы найдете множество продуктов на самый разный вкус!</p>
            </div>
            <div class="main-info2">
                <p class="h1text"><img class="info2-img" src="{% static 'assets/lifestyle.png' %}" alt="">Больше никаких неработающих диет!</p>
                <p class="text">Только здоровое и вкусное питание!</p>
            </div>

            <div id="index-image">
                <img src="{% static 'assets/home_page.png' %}" alt="">
            </div>

        </div>

    </body>

</html>

recsys/templates/postfilter.html
{ load static }

<html lang="ru">

    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Good Food. Catalog</title>
        <link rel="icon" type="image" href="{% static 'assets/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        <link rel="stylesheet" href="{% static 'styles/catalog.css' %}">
    </head>

    <body>
        
        <div id="heading">
            <span>Good Food</span>
        </div>

        <div id="body">
            <div class="navbar">
                <a href="{% url 'index' %}" class="nav-button">Главная</a>
                <a href="{% url 'catalog' %}" class="nav-button">Каталог<div class="nav-button--circle"></div></a>
                {% if user.is_authenticated %}
                    <a href="{% url 'foru' %}" class="nav-button restricted">Для вас</a>
                {% else %}
                    <script src="{ static 'utils/restrict.js' }"></script>
                {% endif %}

                <div class="auth-buttons">
                    {% if user.is_authenticated %}
                        <a href="{% url 'profile' %}" class="auth-button">Профиль</a>
                        <a href="{% url 'logout' %}" class="auth-button">Выйти</a>
                    {% else %}
                        <a href="{% url 'signin' %}" class="auth-button">Вход</a>
                        <a href="{% url 'signup' %}" class="auth-button">Регистрация</a>
                    {% endif %}
                </div>
            </div>

            <script src="{% static 'utils/catalog.js' %}"></script>
            <div class="catalog-content">
                <div class="catalog-navbar">
                    {% for category in categories %}
                        <button data-target="#{{ category.name }}" class="product-button">
                            {% if category.ru_name %}
                                {{ category.ru_name }}
                            {% else %}
                                {{ category.name }}
                            {% endif %}
                        </button>
                    {% endfor %}
                </div>
    
                <div class="filter">
                    <form method="get">
                        <label for="">Фильтр</label>
                        {% csrf_token %}
                        {{ recfilt_form.recfilt }}
                    </form>
                </div>

                <div class="content-area">
                    {% for category in categories %}
                        <div id="{{ category.name }}" class="content-block {% if forloop.first %}active{% endif %}">
                            <div class="product-grid">
                                {% for product in products %}
                                    {% if product.category == category %}
                                        <div class="product-card">
                                            <h3>{{ product.name }}</h3>
                                            <h4>Состав: <br>
                                                Белки: {{ product.proteins }}<br>
                                                Жиры: {{ product.fats }}<br>
                                                Углеводы: {{ product.carbohydrates }}<br>
                                                Калорийность: {{ product.caloricity }}
                                            </h4>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

        </div>

    </body>

</html>

recsys/templates/product_detail.html
{% block content %}
    <div class="product-detail">
        <h1>{{ product.name }}</h1>
        
        <div class="nutrition-info">
            <h4>Пищевая ценность на 100г:</h4>
            <p>Белки: {{ product.proteins }}г</p>
            <p>Жиры: {{ product.fats }}г</p>
            <p>Углеводы: {{ product.carbohydrates }}г</p>
            <p>Калории: {{ product.caloricity }} ккал</p>
        </div>
        <div class="rating-section"></div>
            {% if user.is_authenticated %}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Оценить</button>
                </form>
            {% endif %}
        </div>

    </div>
{% endblock %}

recsys/templates/profile.html
{% load static %}

<html lang="ru">

    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Good Food. profile</title>
        <link rel="icon" type="image" href="{% static 'assets/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        <link rel="stylesheet" href="{% static 'styles/profile.css' %}">
    </head>

    <body>
        
        <div id="heading">
            <span>Good Food</span>
        </div>

        <div id="body">
            <div class="navbar">
                <a href="{% url 'index' %}" class="nav-button">Главная</a>
                <a href="{% url 'catalog' %}" class="nav-button">Каталог</a>
                {% if user.is_authenticated %}
                    <a href="{% url 'foru' %}" class="nav-button restricted">Для вас</a>
                {% else %}
                    <script src="{ static 'utils/restrict.js' }"></script>
                {% endif %}
                
                <div class="auth-buttons">
                    {% if user.is_authenticated %}
                        <a href="{% url 'profile' %}" class="auth-button">Профиль<div class="nav-button--circle"></div></a>
                        <a href="{% url 'logout' %}" class="auth-button">Выйти</a>
                    {% else %}
                        <a href="{% url 'signin' %}" class="auth-button">Вход</a>
                        <a href="{% url 'signup' %}" class="auth-button">Регистрация</a>
                    {% endif %}
                </div>
            </div>

            <div>
                <form method="post" class="profile-container">
                    <h2>Ваши данные</h2>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save-btn">Обновить данные</button>
                </form>

                <div class="excluded-products">
                    <h2>Исключённые продукты</h2>
                    <ul>{% for product in request.user.profile.excluded_products.all %}
                        <li>{{ product.name }}
                            <form method="post" action="{% url 'include_product' product.id %}" style="display:inline;">
                                {% csrf_token %}
                                <button type="submit">Убрать</button>
                            </form>
                        </li>
                        {% empty %}
                            <li>Нет исключённых продуктов.</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="graph">
                <form method="post">
                    {% csrf_token %}
                    {{ weight_form.weight.label_tag }} {{ weight_form.weight }}
                    <button type="submit" name="save_weight">Добавить изменения</button>
                </form>
                <canvas id="weightChart"></canvas>
                <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                <script>
                    const ctx = document.getElementById('weightChart').getContext('2d');
                    const chart = new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: {{ dates|safe }},
                            datasets: [{
                                label: 'Вес (кг)',
                                data: {{ weights|safe }},
                                borderColor: 'blue',
                                fill: false
                            }]
                        },
                        options: {
                            responsive: true,
                            scales: {
                                y: { beginAtZero: false }
                            }
                        }
                    });
                </script>
            </div>

        </div>

    </body>

</html>

recsys/templates/signin.html
{% load static %}

<html lang="ru">

    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Good Food. Sign In</title>
        <link rel="icon" type="image" href="{% static 'assets/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'styles/sign.css' %}">
    </head>

    <body>
        
        <div class="sign-window">
            <h2>Вход</h2>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn">Войти</button>
                <a href="{% url 'index' %}">Вернуться</a>
            </form>
        </div>

    </body>

</html>

recsys/templates/signup.html
{% load static %}

<html lang="ru">

    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Good Food. Sign Up</title>
        <link rel="icon" type="image" href="{% static 'assets/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'styles/sign.css' %}">
    </head>

    <body>
        
        <div class="sign-window">
            <h2>Регистрация</h2>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn">Зарегестрироваться</button>
                <a href="{% url 'index' %}">Вернуться</a>
            </form>
        </div>

    </body>

</html>